Repository cancerogen16/canna, pull requests merged in 2021-08, with the labels that each got.

#119 Feature/new salon methods
  app/Http/Controllers/Api/SalonController.php
  app/Http/Requests/SalonRequest.php
  app/Http/Requests/SalonSearchRequest.php
  app/Policies/SalonPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Traits/ApiResponder.php
  database/seeders/SalonsSeeder.php
  routes/api/salons.php
Labels: back

#138 Сервис загрузки изображений
  .gitignore
  app/Contracts/UploadImageServiceContract.php
  app/Http/Controllers/Api/MasterController.php
  app/Http/Requests/MasterRequest.php
  app/Providers/AppServiceProvider.php
  app/Services/ImageUploadService.php
Labels: back

#140 добавлена страница "Акции" в dashboard салона /dashboard/actions
  resources/js/components/actions/preview/index.js
  resources/js/components/actions/preview/style.js
  resources/js/components/header/index.js
  resources/js/components/navigation/index.js
  resources/js/pages/dashboard/routes.js
  resources/js/pages/dashboard/styles/actions.js
  resources/js/pages/dashboard/views/actions.js
  resources/js/store/action/action.js
  resources/js/store/action/reducer.js
  resources/js/store/index.js
Labels: back

#144 Создан метод resize и убран из загрузки изображений
  app/Contracts/UploadImageServiceContract.php
  app/Http/Controllers/Api/MasterController.php
  app/Services/ImageUploadService.php
Labels: back

#146 Рефакторинг кода store
  resources/js/app.js
  resources/js/components/ListSalon/index.js
  resources/js/components/login/useHukLogin.js
  resources/js/components/registre/useHukReg.js
  resources/js/components/salon/index.js
  resources/js/components/search-salon/index.js
  resources/js/components/userBar/useHukUserBar.js
  resources/js/layout/Dashboard.js
  resources/js/pages/dashboard/views/index.js
  resources/js/pages/public/views/salon.js
  resources/js/routes/Private.js
  resources/js/store/action/action-types.js
  resources/js/store/action/action.js
  resources/js/store/action/reducer.js
  resources/js/store/action/thunks.js
  resources/js/store/auth/actions.js
  resources/js/store/auth/reducer.js
  resources/js/store/auth/thunks.js
  resources/js/store/category/action-types.js
  resources/js/store/category/action.js
  resources/js/store/category/reducer.js
  resources/js/store/category/thunks.js
  resources/js/store/index.js
  resources/js/store/master/action-types.js
  resources/js/store/master/action.js
  resources/js/store/master/reducer.js
  resources/js/store/master/thunks.js
  resources/js/store/records/action-types.js
  resources/js/store/records/action.js
  resources/js/store/records/reducer.js
  resources/js/store/records/thunks.js
  resources/js/store/salon/action-types.js
  resources/js/store/salon/action.js
  resources/js/store/salon/reducer.js
  resources/js/store/salon/thunks.js
  resources/js/store/salons/action-types.js
  resources/js/store/salons/action.js
  resources/js/store/salons/reducer.js
  resources/js/store/salons/thunks.js
  resources/js/store/user/action-types.js
  resources/js/store/user/action.js
  resources/js/store/user/reducer.js
  resources/js/store/user/thunks.js
  resources/js/utils/HTTP.js
Labels: front

#154 Правка вывода изображений
  app/Http/Controllers/Api/MasterController.php
  app/Http/Controllers/Api/SalonController.php
  app/Http/Requests/SalonRequest.php
  app/Services/ImageUploadService.php
  config/image.php
Labels: back

#156 Feature/images services actions
  app/Http/Requests/ActionRequest.php
  app/Http/Requests/CategoryRequest.php
  app/Http/Requests/MasterRequest.php
  app/Http/Requests/ServiceRequest.php
  app/Models/Category.php
  app/Services/ImageUploadService.php
  storage/app/.gitignore
  storage/app/images/.gitignore
  storage/app/images/origin/.gitignore
  storage/app/images/thumbnail/.gitignore
Labels: back

#158 salon image
  app/Http/Controllers/Api/SalonController.php
  resources/js/components/Dashboard/FormSalon/index.js
  resources/js/components/Dashboard/FormSalon/useFormSalon.js
  resources/js/store/salon/thunks.js
Labels: back

#159 thumbnail getServices
  app/Http/Controllers/Api/SalonController.php
Labels: back

#160 thumbnail getMasters
  app/Http/Controllers/Api/SalonController.php
Labels: back

#161 Feature/images to controllers
  app/Http/Controllers/Api/ActionController.php
  app/Http/Controllers/Api/CategoryController.php
  app/Http/Controllers/Api/MasterController.php
  app/Http/Controllers/Api/SalonController.php
  app/Http/Controllers/Api/ServiceController.php
  app/Http/Controllers/Api/UserController.php
Labels: back

#162 Правка вывода отсутствующих изображений
  app/Services/ImageUploadService.php
Labels: back

#170 Метод получает параметры салона: салон, мастеров, услуги, акции
  app/Facades/ImageUpload.php
  app/Http/Controllers/Api/SalonController.php
  app/Models/Salon.php
  config/app.php
  routes/api/salons.php
Labels: back

#175 Feature/salon full
  resources/js/pages/public/huks/useSalon.js
  resources/js/pages/public/views/salon.js
  resources/js/store/master/reducer.js
  resources/js/store/salon/thunks.js
  resources/js/store/services/action.js
  resources/js/store/services/reducer.js
Labels: front

#177 front - dashboard/masters
  resources/js/components/Dashboard/FormMaster/index.js
  resources/js/components/Dashboard/FormMaster/style.js
  resources/js/components/Dashboard/FormMaster/useFormMaster.js
  resources/js/layout/Dashboard.js
  resources/js/pages/dashboard/views/masters.js
  resources/js/store/master/action.js
  resources/js/store/master/reducer.js
  resources/js/store/master/thunks.js
  resources/js/store/salon/action-types.js
  resources/js/store/salon/action.js
Labels: front

#182 Обработка ошибок с сервера
  app/Http/Controllers/Api/AuthController.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/js/components/Dialogs/Alert/index.js
  resources/js/components/Public/Login/index.js
  resources/js/layout/Public.js
  resources/js/layout/index.js
  resources/js/store/auth/thunks.js
  resources/js/store/category/thunks.js
  resources/js/store/error/action-types.js
  resources/js/store/error/action.js
  resources/js/store/error/reducer.js
  resources/js/store/error/useSnack.js
  resources/js/store/index.js
  resources/js/store/master/thunks.js
  resources/js/store/masters/thunks.js
  resources/js/store/records/thunks.js
  resources/js/store/salon/thunks.js
  resources/js/store/salons/thunks.js
  resources/js/store/services/thunks.js
  resources/js/store/user/thunks.js
Labels: front

#188 exceptions in index
  app/Http/Controllers/Api/ActionController.php
  app/Http/Controllers/Api/CalendarController.php
  app/Http/Controllers/Api/CategoryController.php
  app/Http/Controllers/Api/MasterController.php
  app/Http/Controllers/Api/SalonController.php
  app/Http/Controllers/Api/ServiceController.php
Labels: back

#193 sluggabl config created
  config/sluggable.php
Labels: back

#191 Загрузка изображения на сервер
  app/Http/Controllers/Api/ImageController.php
  app/Http/Controllers/Api/MasterController.php
  app/Http/Requests/MasterRequest.php
  app/Models/Salon.php
  resources/js/components/Dashboard/FormMaster/index.js
  resources/js/components/Dashboard/FormMaster/style.js
  resources/js/components/Dashboard/FormMaster/useFormMaster.js
  resources/js/components/Public/MasterPreview/index.js
  resources/js/pages/dashboard/views/masters.js
  resources/js/store/master/thunks.js
  resources/js/store/masters/action.js
  routes/api.php
Labels: front, back

#204 unique file name
  app/Services/ImageUploadService.php
  routes/api.php
Labels: back

#205 schedule service created
  app/Facades/Schedule.php
  app/Http/Controllers/Api/CalendarController.php
  app/Providers/AppServiceProvider.php
  app/Services/ScheduleService.php
  config/app.php
Labels: back

#208 Feature/master update
  resources/js/components/Public/ListSalon/CardSalon/index.js
  resources/js/store/master/thunks.js
  resources/js/store/masters/action-types.js
  resources/js/store/masters/action.js
  resources/js/store/masters/reducer.js
Labels: front

#215 Обновление услуги в списке после редактирования
  resources/js/store/service/thunks.js
  resources/js/store/services/action-types.js
  resources/js/store/services/action.js
  resources/js/store/services/reducer.js
Labels: front

#216 Feature/category select
  resources/js/components/Dashboard/FormService/index.js
  resources/js/components/Dashboard/FormService/style.js
  resources/js/components/Public/ServicePreview/style.js
  resources/js/store/services/action.js
Labels: front

#217 Загрузка фото салона на фронте
  resources/js/components/Dashboard/FormSalon/index.js
  resources/js/components/Dashboard/FormSalon/style.js
  resources/js/components/Dashboard/FormSalon/useFormSalon.js
Labels: front
